### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by akki10** [cloudera/seismichadoop#4]
Hey,

I was trying to run some commands with the seismichadoop and encountered the following error.
It seems some miss match with classes.

Can you please help me out to remove it?

Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.JobContext, but class was expected
    at org.apache.crunch.hadoop.mapreduce.lib.output.CrunchMultipleOutputs.getNamedOutputsList(CrunchMultipleOutputs.java:210)
    at org.apache.crunch.hadoop.mapreduce.lib.output.CrunchMultipleOutputs.checkNamedOutputName(CrunchMultipleOutputs.java:197)
    at org.apache.crunch.hadoop.mapreduce.lib.output.CrunchMultipleOutputs.addNamedOutput(CrunchMultipleOutputs.java:256)
    at org.apache.crunch.io.impl.FileTargetImpl.configureForMapReduce(FileTargetImpl.java:65)
    at org.apache.crunch.io.impl.FileTargetImpl.configureForMapReduce(FileTargetImpl.java:50)
    at org.apache.crunch.impl.mr.plan.MSCROutputHandler.configure(MSCROutputHandler.java:63)
    at org.apache.crunch.io.impl.FileTargetImpl.accept(FileTargetImpl.java:71)
    at org.apache.crunch.impl.mr.plan.MSCROutputHandler.configureNode(MSCROutputHandler.java:51)
    at org.apache.crunch.impl.mr.plan.JobPrototype.build(JobPrototype.java:138)
    at org.apache.crunch.impl.mr.plan.JobPrototype.getCrunchJob(JobPrototype.java:114)
    at org.apache.crunch.impl.mr.plan.MSCRPlanner.plan(MSCRPlanner.java:111)
    at org.apache.crunch.impl.mr.MRPipeline.plan(MRPipeline.java:144)
    at org.apache.crunch.impl.mr.MRPipeline.run(MRPipeline.java:154)
    at org.apache.crunch.impl.mr.MRPipeline.done(MRPipeline.java:183)
    at com.cloudera.seismic.crunch.SUPipeline.run(SUPipeline.java:152)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at com.cloudera.seismic.segy.Main.main(Main.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

**Comment by yjseong** [comment]
If you use eclipse to compile this source,
remove the dependency crunch library  in pom.xml.
After removing add the dependency crunch library using search the library eclipse.
then, compile and run -> OK.

# A pom.xml file in my case as below just only dependency part.

  <dependencies>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-core</artifactId>
      <version>1.0.4</version>
      <scope>provided</scope>
    </dependency>

```
<dependency>
  <groupId>commons-cli</groupId>
  <artifactId>commons-cli</artifactId>
  <version>1.2</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>commons-io</groupId>
  <artifactId>commons-io</artifactId>
  <version>2.1</version>
</dependency>


<dependency>
  <groupId>commons-lang</groupId>
  <artifactId>commons-lang</artifactId>
  <version>2.4</version>
</dependency>

<dependency>
  <groupId>commons-httpclient</groupId>
  <artifactId>commons-httpclient</artifactId>
  <version>3.0.1</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>junit</groupId>
  <artifactId>junit</artifactId>
  <version>3.8.1</version>
  <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.apache.crunch</groupId>
    <artifactId>crunch-core</artifactId>
    <version>0.11.0-hadoop2</version>
</dependency>
```

#   </dependencies>
